[package]
name = "mincorr_cli"
version = "0.2.1"
edition = "2024"

[[bin]]
name = "mincorr_cli"
path = "src/main.rs"

[dependencies]
csv = "1.4.0"
flate2 = "1.1.5"
mincorr_core = { path = "../core" }
ndarray = "0.17.1"
rayon = "1.11.0"
strum = "0.27.2"
strum_macros = "0.27.2"
tar = "0.4.44"
