[package]
name = "mincorrpy"
version = "0.2.1"
edition = "2024"
license = "GPL-2.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
mincorr = { path = "../core" }
ndarray = "0.17.1"
numpy = "0.27.1"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
