[package]
name = "mincorr"
version = "0.2.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
mincorr_core = { path = "../core" }
ndarray = "0.17.1"
numpy = "0.27.1"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
